language: scala

before_install:  curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh
install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version

env:
  - TRAVIS_JDK=8
  - TRAVIS_JDK=11

scala:
  - 2.10.7
  - 2.12.10
  - 2.13.1

script: sbt ++$TRAVIS_SCALA_VERSION test publishLocal scalafmtCheckAll scalafmtSbtCheck

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
    - "$HOME/.jabba/jdk"

before_cache:
  - rm -rf $HOME/.ivy2/cache/com.typesafe.play/play-doc*
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

notifications:
  slack:
    secure: eSXNye/c+jVCFfB9E28AmXaOFiboQLkEINHXRfkcniVyQ1EVQGVoX2qXstkJmm9GRaUGuQkTi0mg8cRbXWff/3kn2H2O73Wot80E1H6YgkYm7lJ+ZYChxhiLn0j1YK8IPropdKGmtPtBJ+1yy7Radm6UUGDFVAGpIV9ibNAWXJM=
